[package]
name = "pipeline"
version = "0.1.0"
authors = ["Brian L. Troutwine <brian@troutwine.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.futures]
version = "0.3"
default-features = false
features = ["std"]

[dependencies.tokio-stream]
version = "0.1"
features = ["io-util"]

[dependencies.tokio]
version = "1.4"
features = ["full", "sync"]